# Generated by Django 4.2.5 on 2023-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/rooms/'),
        ),
    ]
